### ISSUE TITLE
Single Image Relighting

### ISSUE THREAD

**Issue by hhlsygmz** [Brummi/derender3d#2]
Excellent work!
I was wondering how to apply target lighting to single source image like Fig.6 in the paper?
Could you teach me how to do that? Thanks!

**Comment by Brummi** [comment]
Hi Donkdot,
thanks for being interested in out work! 
You can pass the target lighting directly to the model in the forward pass. Examples for this can be found in the relighting scripts, e.g. in `scripts/video_relighting_celebahq.py`.
Concretely, this will give you a relit reconstruction:

`model.forward(data_dict_, light=light)`

Best,
Felix

**Comment by hhlsygmz** [comment]
Thank you so much !
