### ISSUE TITLE
cannot download pre-trained model

### ISSUE THREAD

**Issue by anewusername77** [Brummi/derender3d#4]
Thanks for sharing your excellent work!
I want to test this model, but I can't download it by using ```set_up/download_model.sh```(received nothing), so I tried with entering website ```https://www.robots.ox.ac.uk/~vgg/research/derender3d/data```, but received ```You don't have permission to access this resource.```
Can you help? thanks a lot.

**Comment by Brummi** [comment]
Hi,
thanks for your interest in our work.
For the setup script, you need to pass either "celebahq" or "co3d" like so:

```sh
setup/download_model.sh celebahq
# or
setup/download_model.sh co3d
```
I just tested it and it works fine.

Best,
Felix

**Comment by anewusername77** [comment]
I just tried, it seems like a problem caused by proxy, already solved! thanks so much!!
