### ISSUE TITLE
Where to download CelebAHQ cropped / extracted / unsup3d

### ISSUE THREAD

**Issue by rshiv2** [Brummi/derender3d#7]
The script you've provided in ```setup/download_processed_celebahq.sh``` does not provide links for downloading the CelebAHQ dataset. What links should we use if we want to train the network on this dataset? Thanks!

**Comment by Brummi** [comment]
Unfortunately, do to privacy and licensing concerns, we have decided not to provide download links for the CelebA-HQ based data.
You can manually download CelebA-HQ. The code for processing the data will be uploaded in the future. We are currently working on publishing it.
